name: InfluxDB Test

on:
  push:
    branches:
      - main

jobs:
  test-win-influxdb:
    runs-on: windows-latest
    steps:
    - name: Use the secret
      run: python test-win-influxdb/module1/hello.py #echo ${{ secrets.INFLUXDB_URL }}
